#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx ng lint                                               #lint the project
npx ng test --watch=false --browsers ChromeHeadless       #test the project to check changes.
npx ng build --configuration=production                   #build the project
rm -rf dist                                               #delete the dist folder created.
